=== EntropiaFox/astranauta.github.io/test/schema/class/foundry.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "foundry-class.json",
	"version": "1.3.5",
	"type": "object",
	"definitions": {
		"entryDataObject": {
			"description": "Additional \"5etools-type\" data to be stored on the entry.",
			"type": "object",
			"properties": {
				"languageProficiencies": {
					"$ref": "../util.json#/definitions/languageProficiencies"
				},
				"skillProficiencies": {
					"$ref": "../util.json#/definitions/skillProficiencies"
				},
				"weaponProficiencies": {
					"$ref": "../util.json#/definitions/weaponProficiencies"
				},
				"armorProficiencies": {
					"$ref": "../util.json#/definitions/armorProficiencies"
				},
				"toolProficiencies": {
					"$ref": "../util.json#/definitions/toolProficiencies"
				},
				"savingThrowProficiencies": {
					"$ref": "../util.json#/definitions/savingThrowProficiencies"
				},
				"expertise": {
					"$ref": "../util.json#/definitions/expertise"
				},
				"resist": {
					"$ref": "../util.json#/definitions/damageResistArrayPlayer"
				},
				"immune": {
					"$ref": "../util.json#/definitions/damageImmunityArrayPlayer"
				},
				"vulnerable": {
					"$ref": "../util.json#/definitions/damageVulnerabilityArrayPlayer"
				},
				"conditionImmune": {
					"$ref": "../util.json#/definitions/conditionImmunityArrayPlayer"
				},
				"resources": {
					"$ref": "../util.json#/definitions/resourcesArray"
				},
				"senses": {
					"$ref": "../util.json#/definitions/sensesArray"
				}
			},
			"additionalProperties": false
		}
	},
	"properties": {
		"class": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "../entry.json"
						}
					},
					"entryData": {
						"$ref": "#/definitions/entryDataObject"
					},
					"data": {
						"$ref": "../util.json#/definitions/foundryDataObject"
					},
					"flags": {
						"$ref": "../util.json#/definitions/foundryFlagsObject"
					},
					"advancement": {
						"$ref": "../util.json#/definitions/foundryAdvancementsArray"
					},
					"chooseData": {
						"type": "array",
						"items": {
							"$ref": "../util.json#/definitions/foundryDataObject"
						}
					},
					"isChooseDataRenderEntries": {
						"type": "boolean"
					},
					"isIgnored": {
						"const": true
					},
					"actorDataMod": {
						"type": "object"
					},
					"actorTokenMod": {
						"type": "object"
					},
					"effects": {
						"$ref": "../util.json#/definitions/foundryEffectsArray"
					},
					"img": {
						"type": "string"
					},
					"subEntities": {
						"$ref": "../util.json#/definitions/foundrySubEntitiesObject"
					}
				},
				"required": [
					"name",
					"source"
				],
				"additionalProperties": false
			}
		},
		"subclass": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"className": {
						"type": "string"
					},
					"classSource": {
						"type": "string"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "../entry.json"
						}
					},
					"entryData": {
						"$ref": "#/definitions/entryDataObject"
					},
					"data": {
						"$ref": "../util.json#/definitions/foundryDataObject"
					},
					"flags": {
						"$ref": "../util.json#/definitions/foundryFlagsObject"
					},
					"advancement": {
						"$ref": "../util.json#/definitions/foundryAdvancementsArray"
					},
					"chooseData": {
						"type": "array",
						"items": {
							"$ref": "../util.json#/definitions/foundryDataObject"
						}
					},
					"isChooseDataRenderEntries": {
						"type": "boolean"
					},
					"isIgnored": {
						"const": true
					},
					"actorDataMod": {
						"type": "object"
					},
					"actorTokenMod": {
						"type": "object"
					},
					"effects": {
						"$ref": "../util.json#/definitions/foundryEffectsArray"
					},
					"img": {
						"type": "string"
					},
					"subEntities": {
						"$ref": "../util.json#/definitions/foundrySubEntitiesObject"
					}
				},
				"required": [
					"name",
					"source",
					"className",
					"classSource"
				],
				"additionalProperties": false
			}
		},
		"classFeature": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"className": {
						"type": "string"
					},
					"classSource": {
						"type": "string"
					},
					"level": {
						"type": "integer"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "../entry.json"
						}
					},
					"entryData": {
						"$ref": "#/definitions/entryDataObject"
					},
					"data": {
						"$ref": "../util.json#/definitions/foundryDataObject"
					},
					"flags": {
						"$ref": "../util.json#/definitions/foundryFlagsObject"
					},
					"chooseData": {
						"type": "array",
						"items": {
							"$ref": "../util.json#/definitions/foundryDataObject"
						}
					},
					"isChooseDataRenderEntries": {
						"type": "boolean"
					},
					"isIgnored": {
						"const": true
					},
					"actorDataMod": {
						"type": "object"
					},
					"actorTokenMod": {
						"type": "object"
					},
					"effects": {
						"$ref": "../util.json#/definitions/foundryEffectsArray"
					},
					"img": {
						"type": "string"
					},
					"subEntities": {
						"$ref": "../util.json#/definitions/foundrySubEntitiesObject"
					}
				},
				"required": [
					"name",
					"source",
					"className",
					"classSource",
					"level"
				],
				"additionalProperties": false
			}
		},
		"subclassFeature": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"className": {
						"type": "string"
					},
					"classSource": {
						"type": "string"
					},
					"level": {
						"type": "integer"
					},
					"subclassShortName": {
						"type": "string"
					},
					"subclassSource": {
						"type": "string"
					},
					"entries": {
						"type": "array",
						"items": {
							"$ref": "../entry.json"
						}
					},
					"entryData": {
						"$ref": "#/definitions/entryDataObject"
					},
					"data": {
						"$ref": "../util.json#/definitions/foundryDataObject"
					},
					"flags": {
						"$ref": "../util.json#/definitions/foundryFlagsObject"
					},
					"chooseData": {
						"type": "array",
						"items": {
							"$ref": "../util.json#/definitions/foundryDataObject"
						}
					},
					"isChooseDataRenderEntries": {
						"type": "boolean"
					},
					"isIgnored": {
						"const": true
					},
					"actorDataMod": {
						"type": "object"
					},
					"actorTokenMod": {
						"type": "object"
					},
					"effects": {
						"$ref": "../util.json#/definitions/foundryEffectsArray"
					},
					"img": {
						"type": "string"
					},
					"subEntities": {
						"$ref": "../util.json#/definitions/foundrySubEntitiesObject"
					}
				},
				"required": [
					"name",
					"source",
					"className",
					"classSource",
					"level",
					"subclassShortName",
					"subclassSource"
				],
				"additionalProperties": false
			}
		}
	},
	"required": [
		"class",
		"subclass",
		"classFeature",
		"subclassFeature"
	],
	"additionalProperties": false
}

=== EntropiaFox/astranauta.github.io/data/class/foundry.json
{
	"class": [
		{
			"name": "Sorcerer",
			"source": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "sorcery-points",
						"type": "number",
						"scale": {
							"2": {
								"value": 2
							},
							"3": {
								"value": 3
							},
							"4": {
								"value": 4
							},
							"5": {
								"value": 5
							},
							"6": {
								"value": 6
							},
							"7": {
								"value": 7
							},
							"8": {
								"value": 8
							},
							"9": {
								"value": 9
							},
							"10": {
								"value": 10
							},
							"11": {
								"value": 11
							},
							"12": {
								"value": 12
							},
							"13": {
								"value": 13
							},
							"14": {
								"value": 14
							},
							"15": {
								"value": 15
							},
							"16": {
								"value": 16
							},
							"17": {
								"value": 17
							},
							"18": {
								"value": 18
							},
							"19": {
								"value": 19
							},
							"20": {
								"value": 20
							}
						}
					},
					"title": "Sorcery Points"
				}
			]
		}
	],
	"subclass": [
		{
			"name": "College of Whispers",
			"source": "XGE",
			"className": "Bard",
			"classSource": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "psychic-blades",
						"type": "dice",
						"scale": {
							"3": {
								"n": 2,
								"die": 6
							},
							"5": {
								"n": 3,
								"die": 6
							},
							"10": {
								"n": 5,
								"die": 6
							},
							"15": {
								"n": 8,
								"die": 6
							}
						}
					},
					"title": "Psychic Blades"
				}
			]
		},
		{
			"name": "Death Domain",
			"source": "DMG",
			"className": "Cleric",
			"classSource": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "divine-strike",
						"type": "dice",
						"scale": {
							"8": {
								"n": 1,
								"die": 8
							},
							"14": {
								"n": 2,
								"die": 8
							}
						}
					},
					"title": "Divine Strike"
				}
			]
		},
		{
			"name": "Forge Domain",
			"source": "XGE",
			"className": "Cleric",
			"classSource": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "divine-strike",
						"type": "dice",
						"scale": {
							"8": {
								"n": 1,
								"die": 8
							},
							"14": {
								"n": 2,
								"die": 8
							}
						}
					},
					"title": "Divine Strike"
				}
			]
		},
		{
			"name": "Nature Domain",
			"source": "PHB",
			"className": "Cleric",
			"classSource": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "divine-strike",
						"type": "dice",
						"scale": {
							"8": {
								"n": 1,
								"die": 8
							},
							"14": {
								"n": 2,
								"die": 8
							}
						}
					},
					"title": "Divine Strike"
				}
			]
		},
		{
			"name": "Order Domain",
			"source": "TCE",
			"className": "Cleric",
			"classSource": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "divine-strike",
						"type": "dice",
						"scale": {
							"8": {
								"n": 1,
								"die": 8
							},
							"14": {
								"n": 2,
								"die": 8
							}
						}
					},
					"title": "Divine Strike"
				}
			]
		},
		{
			"name": "Trickery Domain",
			"source": "PHB",
			"className": "Cleric",
			"classSource": "PHB",
			"advancement": [
				{
					"type": "ScaleValue",
					"configuration": {
						"identifier": "divine-strike",
						"type": "dice",
						"scale": {
							"8": {
								"n": 1,
								"die": 8
							},
							"14": {
								"n": 2,
								"die": 8
							}
						}
					},
					"title": "Divine Strike"
				}
			]
		}
	],
	"classFeature": [
		{
			"name": "Unarmored Movement",
			"source": "PHB",
			"className": "Monk",
			"classSource": "PHB",
			"level": 2,
			"effects": [
				{
					"name": "Unarmored Movement",
					"changes": [
						{
							"key": "data.attributes.movement.walk",
							"mode": "ADD",
							"value": "sign(@attributes.movement.walk) * @scale.monk.unarmored-movement"
						},
						{
							"key": "data.attributes.movement.burrow",
							"mode": "ADD",
							"value": "sign(@attributes.movement.burrow) * @scale.monk.unarmored-movement"
						},
						{
							"key": "data.attributes.movement.climb",
							"mode": "ADD",
							"value": "sign(@attributes.movement.climb) * @scale.monk.unarmored-movement"
						},
						{
							"key": "data.attributes.movement.fly",
							"mode": "ADD",
							"value": "sign(@attributes.movement.fly) * @scale.monk.unarmored-movement"
						},
						{
							"key": "data.attributes.movement.swim",
							"mode": "ADD",
							"value": "sign(@attributes.movement.swim) * @scale.monk.unarmored-movement"
						}
					]
				}
			]
		},
		{
			"name": "Metamagic",
			"source": "PHB",
			"className": "Sorcerer",
			"classSource": "PHB",
			"level": 3,
			"entries": [
				"At 3rd level, you gain the ability to twist your spells to suit your needs. You gain two Metamagic options of your choice. You gain another one at 10th and 17th level.",
				"You can use only one Metamagic option on a spell when you cast it, unless otherwise noted."
			]
		},
		{
			"name": "Metamagic Options",
			"source": "UAClassFeatureVariants",
			"className": "Sorcerer",
			"classSource": "PHB",
			"level": 3,
			"isIgnored": true
		},
		{
			"name": "Metamagic Options",
			"source": "TCE",
			"className": "Sorcerer",
			"classSource": "PHB",
			"level": 3,
			"isIgnored": true
		},
		{
			"name": "Metamagic",
			"source": "PHB",
			"className": "Sorcerer",
			"classSource": "PHB",
			"level": 10,
			"isIgnored": true
		},
		{
			"name": "Metamagic",
			"source": "PHB",
			"className": "Sorcerer",
			"classSource": "PHB",
			"level": 17,
			"isIgnored": true
		},
		{
			"name": "Infusions Known",
			"source": "TCE",
			"className": "Artificer",
			"classSource": "TCE",
			"level": 2,
			"isIgnored": true
		},
		{
			"name": "Eldritch Invocations",
			"source": "PHB",
			"className": "Warlock",
			"classSource": "PHB",
			"level": 2,
			"entries": [
				"In your study of occult lore, you have unearthed eldritch invocations, fragments of forbidden knowledge that imbue you with an abiding magical ability.",
				"At 2nd level, you gain two eldritch invocations of your choice. Your invocation options are detailed at the end of the class description. When you gain certain warlock levels, you gain additional invocations of your choice, as shown in the Invocations Known column of the Warlock table.",
				"Additionally, when you gain a level in this class, you can choose one of the invocations you know and replace it with another invocation that you could learn at that level.",
				"If an eldritch invocation has prerequisites, you must meet them to learn it. You can learn the invocation at the same time that you meet its prerequisites. A level prerequisite refers to your level in this class."
			]
		},
		{
			"name": "Martial Arts",
			"source": "PHB",
			"className": "Monk",
			"classSource": "PHB",
			"level": 1,
			"subEntities": {
				"item": [
					{
						"name": "Unarmed Strike (Monk)",
						"source": "PHB",
						"page": 76,
						"srd": true,
						"type": "M",
						"rarity": "none",
						"weaponCategory": "simple",
						"entries": [
							{
								"type": "quote",
								"entries": [
									"Tether even a roasted chicken."
								],
								"by": "Yamamoto Tsunetomo",
								"from": "Hagakure Kikigaki"
							}
						],
						"foundryData": {
							"equipped": true,
							"damage.parts": [
								[
									"1d@(scale.monk.die) + @mod",
									"bludgeoning"
								]
							],
							"ability": "dex"
						}
					}
				]
			}
		},
		{
			"name": "Fast Movement",
			"source": "PHB",
			"className": "Barbarian",
			"classSource": "PHB",
			"level": 5,
			"effects": [
				{
					"changes": [
						{
							"key": "data.attributes.movement.walk",
							"mode": "ADD",
							"value": 10
						}
					]
				}
			]
		},
		{
			"name": "Expertise",
			"source": "PHB",
			"className": "Rogue",
			"classSource": "PHB",
			"level": 1,
			"entryData": {
				"expertise": [
					{
						"anyProficientSkill": 2
					},
					{
						"anyProficientSkill": 1,
						"thieves' tools": true
					}
				]
			}
		},
		{
			"name": "Expertise",
			"source": "PHB",
			"className": "Rogue",
			"classSource": "PHB",
			"level": 6,
			"entryData": {
				"expertise": [
					{
						"anyProficientSkill": 2
					},
					{
						"anyProficientSkill": 1,
						"thieves' tools": true
					}
				]
			}
		},
		{
			"name": "Expertise",
			"source": "PHB",
			"className": "Bard",
			"classSource": "PHB",
			"level": 3,
			"entryData": {
				"expertise": [
					{
						"anyProficientSkill": 2
					}
				]
			}
		},
		{
			"name": "Expertise",
			"source": "PHB",
			"className": "Bard",
			"classSource": "PHB",
			"level": 10,
			"entryData": {
				"expertise": [
					{
						"anyProficientSkill": 2
					}
				]
			}
		},
		{
			"name": "Primal Knowledge",
			"source": "TCE",
			"className": "Barbarian",
			"classSource": "PHB",
			"level": 3,
			"entryData": {
				"skillProficiencies": [
					{
						"choose": {
							"from": [
								"animal handling",
								"athletics",
								"intimidation",
								"nature",
								"perception",
								"survival"
							]
						}
					}
				]
			}
		},
		{
			"name": "Bonus Proficiencies",
			"source": "TCE",
			"className": "Spellcaster Sidekick",
			"classSource": "TCE",
			"level": 1,
			"entryData": {
				"skillProficiencies": [
					{
						"choose": {
							"from": [
								"arcana",
								"history",
								"insight",
								"investigation",
								"medicine",
								"performance",
								"persuasion",
								"religion"
							],
							"count": 2
						}
					}
				]
			}
		},
		{
